name: AUTO - Main to Development

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - run: echo "⚡ This automerge job was triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 Running job on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🚀 The workflow is now ready to start."

      - name: main to core-dev
        if: "contains(github.event.head_commit.message, 'core/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: main to m-core-dev
        if: "contains(github.event.head_commit.message, 'm-core/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: m-core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: main to taskmapper-dev
        if: "contains(github.event.head_commit.message, 'tm/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: taskmapper-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: main to m-taskmapper-dev
        if: "contains(github.event.head_commit.message, 'm-tm/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: m-taskmapper-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
