name: automerge main to development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: merge main to development
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: development to core-dev
        if: "contains(github.event.head_commit.message, 'core/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: development
          target-branch: core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: development to m-core-dev
        if: "contains(github.event.head_commit.message, 'm-core/')"
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: development
          target-branch: m-core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
