name: automerge development to live devs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  automerge_core_dev:
    runs-on: ubuntu-latest
    # if: "startsWith(github.event.head_commit.message, 'core_')"
    steps:
      - uses: actions/checkout@v3

      - name: development to core-dev
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: development
          target-branch: core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge_m_core_dev:
    runs-on: ubuntu-latest
    # if: "startsWith(github.event.head_commit.message, 'm-core_')"
    steps:
      - uses: actions/checkout@v3

      - name: development to m-core-dev
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: development
          target-branch: m-core-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
