name: AUTO - get hotfix in main

on:
  push:
    branches: ["pre-production"]
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: merge to main
        if: startsWith(github.event.head_commit.message, 'hotfix:')
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: pre-production
          target-branch: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
