name: AUTO - cherry-pick hotfix into main

on:
  push:
    branches: ["pre-production"]
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cherry-pick to main
        if: startsWith(github.event.head_commit.message, 'hotfix:')
        uses: carloscastrojumo/github-cherry-pick-action@bb0869df47c27be4ae4c7a2d93d22827aa5a0054
        with:
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
