name: MANUAL - Staging to Production

on:
  workflow_dispatch:
    branches: ["staging"]
    inputs:
      core:
        type: boolean
        description: staging --> core-prod
        default: true
      m_core:
        type: boolean
        description: staging --> m-core-prod
        default: true
      taskmapper:
        type: boolean
        description: staging --> taskmapper-prod
        default: true
      m_taskmapper:
        type: boolean
        description: staging --> m-taskmapper-prod
        default: true

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - run: echo "⚡ This merge job was manually triggered by ${{ github.actor }}."
      - run: echo "🐧 Running job on a ${{ runner.os }} server."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "⏬ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🚀 The workflow is now ready to start."

      - name: merge staging to core-prod
        if: ${{ github.event.inputs.core == 'true' }}
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: staging
          target-branch: core-prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: merge staging to m-core-prod
        if: ${{ github.event.inputs.m_core == 'true' }}
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: staging
          target-branch: m-core-prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: merge staging to taskmapper-prod
        if: ${{ github.event.inputs.taskmapper == 'true' }}
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: staging
          target-branch: taskmapper-prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: merge staging to m-taskmapper-prod
        if: ${{ github.event.inputs.m_taskmapper == 'true' }}
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: staging
          target-branch: m-taskmapper-prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "⏹ .End of job. Status - ${{ job.status }}."
