name: MANUAL - Main to Staging

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - run: echo "⚡ This merge job was manually triggered by ${{ github.actor }}."
      - run: echo "🐧 Running job on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "⏬ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🚀 The workflow is now ready to start."

      - name: merge main to staging
        uses: tukasz/direct-merge-action@b7882b0c66df6376596a91f117272c1ba2d5f867
        with:
          source-branch: main
          target-branch: staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "⏹ End of job. Status: ${{ job.status }}."
